"""
backend/engine/private/sec/__init__.py
========================================
SEC EDGAR Filing, Raw XBRL & Canonical Concept Resolver Module (Phase 8A + 8B.1 + 8B.2A).
"""

from backend.engine.private.sec.cik import format_cik_for_path, normalize_cik
from backend.engine.private.sec.client import (
    DEFAULT_SENTINAX_SAFETY_RPS,
    SEC_OFFICIAL_MAX_RPS,
    SECEdgarClient,
    SECRateLimiter,
    get_shared_sec_rate_limiter,
    reset_shared_sec_rate_limiter,
)
from backend.engine.private.sec.company_facts import (
    SECCompanyFactsParser,
    SECCompanyFactsProvider,
    parse_sec_decimal,
)
from backend.engine.private.sec.concept_resolver import (
    SECConceptResolver,
    classify_form_role,
    validate_unit_compatibility,
)
from backend.engine.private.sec.concepts import (
    CanonicalSECConceptDefinition,
    ConceptVariant,
    FormRole,
    MatchStrength,
    SECConceptMatchStatus,
    StatementFamily,
    UnitClass,
    VerificationStatus,
    get_initial_canonical_concept_definitions,
)
from backend.engine.private.sec.discovery import (
    SECTickerCandidate,
    SECTickerDiscoveryService,
)
from backend.engine.private.sec.lineage import (
    create_fact_filing_links,
    get_fact_acceptance_timestamp,
    get_fact_source_available_at,
    resolve_fact_filing_lineage,
)
from backend.engine.private.sec.models import (
    PeriodType,
    SECCanonicalFactCandidate,
    SECFactFilingLinkRecord,
    SECFilingRecord,
    SECRawFactRecord,
    SECResource,
    SECSubmissionMetadata,
    build_archive_url,
    build_company_facts_url,
    build_submissions_url,
)
from backend.engine.private.sec.period_context import (
    ANNUAL_MAX_DAYS,
    ANNUAL_MIN_DAYS,
    QUARTER_MAX_DAYS,
    QUARTER_MIN_DAYS,
    SUPPORTED_PRIMARY_FORM_ROLES,
    YTD_6M_MAX_DAYS,
    YTD_6M_MIN_DAYS,
    YTD_9M_MAX_DAYS,
    YTD_9M_MIN_DAYS,
    SECEconomicPeriodKind,
    SECPeriodAlignmentStatus,
    SECPeriodClassifier,
    SECPeriodGroupingResult,
    SECPeriodizedFactCandidate,
    build_economic_group_key,
    group_periodized_candidates,
)
from backend.engine.private.sec.submissions import (
    SECSubmissionsFetchResult,
    SECSubmissionsParser,
    SECSubmissionsProvider,
    parse_sec_boolean,
    parse_sec_date,
    parse_sec_datetime_hardened,
)
from backend.engine.private.sec.winner_resolver import (
    FilingDisclosureComparison,
    SECWinnerResolutionMode,
    SECWinnerResolutionResult,
    SECWinnerResolver,
    SECWinnerStatus,
    compare_filing_disclosure_order,
    get_semantic_quality_rank,
    validate_company_facts_snapshot,
)
from backend.engine.private.sec.fiscal_series import (
    SECDerivationEligibilityStatus,
    SECFiscalSeriesStatus,
    SECFiscalSeriesConflict,
    SECFiscalSeriesPoint,
    SECFiscalSeries,
    SECQuarterDerivationEligibility,
    SECIntervalMatchResult,
    SECFiscalSeriesAssembler,
    SECFiscalSeriesEvaluator,
    _effective_inclusive_duration,
    _check_standalone_q2_interval,
    _check_standalone_q3_interval,
)
from backend.engine.private.sec.quarter_derivation import (
    SECQuarterDerivationStatus,
    SECQuarterDerivationResult,
    SECQuarterDeriver,
    _subtract_decimal_exact,
    _compute_derivation_key,
)


__all__ = [
    "normalize_cik",
    "format_cik_for_path",
    "PeriodType",
    "SECResource",
    "SECFilingRecord",
    "SECRawFactRecord",
    "SECFactFilingLinkRecord",
    "SECCanonicalFactCandidate",
    "SECSubmissionMetadata",
    "SECSubmissionsFetchResult",
    "build_submissions_url",
    "build_company_facts_url",
    "build_archive_url",
    "SECRateLimiter",
    "SECEdgarClient",
    "get_shared_sec_rate_limiter",
    "reset_shared_sec_rate_limiter",
    "SEC_OFFICIAL_MAX_RPS",
    "DEFAULT_SENTINAX_SAFETY_RPS",
    "SECSubmissionsParser",
    "SECSubmissionsProvider",
    "parse_sec_datetime_hardened",
    "parse_sec_date",
    "parse_sec_boolean",
    "SECCompanyFactsParser",
    "SECCompanyFactsProvider",
    "parse_sec_decimal",
    "create_fact_filing_links",
    "resolve_fact_filing_lineage",
    "get_fact_acceptance_timestamp",
    "get_fact_source_available_at",
    "SECTickerCandidate",
    "SECTickerDiscoveryService",
    "UnitClass",
    "MatchStrength",
    "StatementFamily",
    "VerificationStatus",
    "FormRole",
    "SECConceptMatchStatus",
    "ConceptVariant",
    "CanonicalSECConceptDefinition",
    "get_initial_canonical_concept_definitions",
    "SECConceptResolver",
    "classify_form_role",
    "validate_unit_compatibility",
    "SECEconomicPeriodKind",
    "SECPeriodAlignmentStatus",
    "SECPeriodizedFactCandidate",
    "SECPeriodGroupingResult",
    "SECPeriodClassifier",
    "build_economic_group_key",
    "group_periodized_candidates",
    "ANNUAL_MIN_DAYS",
    "ANNUAL_MAX_DAYS",
    "QUARTER_MIN_DAYS",
    "QUARTER_MAX_DAYS",
    "YTD_6M_MIN_DAYS",
    "YTD_6M_MAX_DAYS",
    "SUPPORTED_PRIMARY_FORM_ROLES",
    "SECWinnerResolutionMode",
    "SECWinnerStatus",
    "FilingDisclosureComparison",
    "SECWinnerResolutionResult",
    "SECWinnerResolver",
    "compare_filing_disclosure_order",
    "validate_company_facts_snapshot",
    "get_semantic_quality_rank",
    "SECDerivationEligibilityStatus",
    "SECFiscalSeriesStatus",
    "SECFiscalSeriesConflict",
    "SECFiscalSeriesPoint",
    "SECFiscalSeries",
    "SECQuarterDerivationEligibility",
    "SECIntervalMatchResult",
    "SECFiscalSeriesAssembler",
    "SECFiscalSeriesEvaluator",
    "_effective_inclusive_duration",
    "_check_standalone_q2_interval",
    "_check_standalone_q3_interval",
    "SECQuarterDerivationStatus",
    "SECQuarterDerivationResult",
    "SECQuarterDeriver",
    "_subtract_decimal_exact",
    "_compute_derivation_key",
]


