-- ==========================================
-- AI Portfolio Manager - Supabase Schema
-- ==========================================

-- 1. Legacy Portfolio Watchlists Table (per-user ticker list; NOT the private-engine public.portfolios aggregate)
CREATE TABLE IF NOT EXISTS public.legacy_portfolio_watchlists (
    user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    tickers jsonb NOT NULL DEFAULT '[]'::jsonb,
    updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.legacy_portfolio_watchlists ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own portfolio" 
    ON public.legacy_portfolio_watchlists FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own portfolio" 
    ON public.legacy_portfolio_watchlists FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own portfolio" 
    ON public.legacy_portfolio_watchlists FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own portfolio" 
    ON public.legacy_portfolio_watchlists FOR DELETE
    USING (auth.uid() = user_id);


-- 2. Paper Trades Table
CREATE TABLE IF NOT EXISTS public.paper_trades (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    symbol text NOT NULL,
    order_type text NOT NULL CHECK (order_type IN ('BUY', 'SELL')),
    target_weight numeric NOT NULL,
    execution_price numeric DEFAULT 0.0,
    timestamp timestamptz DEFAULT now()
);

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_paper_trades_user_timestamp ON public.paper_trades(user_id, timestamp DESC);

-- Enable RLS
ALTER TABLE public.paper_trades ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own trades" 
    ON public.paper_trades FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own trades" 
    ON public.paper_trades FOR INSERT 
    WITH CHECK (auth.uid() = user_id);


-- 3. Alerts Table
CREATE TABLE IF NOT EXISTS public.alerts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    ticker text NOT NULL,
    message text NOT NULL,
    created_at timestamptz DEFAULT now(),
    is_read boolean DEFAULT false
);

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_alerts_user_created ON public.alerts(user_id, created_at DESC);

-- Enable RLS
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own alerts" 
    ON public.alerts FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own alerts" 
    ON public.alerts FOR UPDATE 
    USING (auth.uid() = user_id);


-- 4. User Settings Table
CREATE TABLE IF NOT EXISTS public.user_settings (
    user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    telegram_chat_id text,
    risk_tolerance text DEFAULT 'Orta' CHECK (risk_tolerance IN ('Düşük', 'Orta', 'Yüksek')),
    role text DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    subscription_tier text DEFAULT 'free' CHECK (subscription_tier IN ('free', 'pro')),
    billing_cycle_start timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own settings" 
    ON public.user_settings FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own settings" 
    ON public.user_settings FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own settings" 
    ON public.user_settings FOR UPDATE 
    USING (auth.uid() = user_id);


-- 5. Portfolio Snapshots Table
CREATE TABLE IF NOT EXISTS public.portfolio_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    total_value numeric NOT NULL,
    cash_balance numeric NOT NULL DEFAULT 0.0,
    timestamp timestamptz DEFAULT now()
);

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_portfolio_snapshots_user_time ON public.portfolio_snapshots(user_id, timestamp DESC);

-- Enable RLS
ALTER TABLE public.portfolio_snapshots ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own snapshots" 
    ON public.portfolio_snapshots FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own snapshots" 
    ON public.portfolio_snapshots FOR INSERT 
    WITH CHECK (auth.uid() = user_id);


-- 6. LLM Usage Logs Table
CREATE TABLE IF NOT EXISTS public.llm_usage_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    prompt_tokens integer NOT NULL DEFAULT 0,
    completion_tokens integer NOT NULL DEFAULT 0,
    cost_usd numeric NOT NULL DEFAULT 0.0,
    timestamp timestamptz DEFAULT now()
);

-- Index for performance tracking
CREATE INDEX IF NOT EXISTS idx_llm_usage_logs_user_time ON public.llm_usage_logs(user_id, timestamp DESC);

-- Enable RLS
ALTER TABLE public.llm_usage_logs ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Users can view their own usage logs
CREATE POLICY "Users can view their own usage logs" 
    ON public.llm_usage_logs FOR SELECT 
    USING (auth.uid() = user_id);

-- Only Admins should be able to see ALL table through dashboard logic in backend (which skips RLS using service role if needed), or we can grant explicit policy if required.
-- However, for simple dashboarding inside backend router using service role skipped RLS anyway.
-- To allow users or admins to view, a policy that allows admins to view everything can be added if we can resolve admin check via JWT.
-- Since backend bypasses RLS using service role to fetch statistics, this policy handles normal user lookups.
